[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "BDSP Research Index"
authors = [{name = "Team Renegade", email = "Placeholder"}]
dynamic = ["version", "description"]
